name: business_logics
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  image_picker: ^1.0.7
  http: ^1.1.0
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.7
  url_launcher: ^6.2.4
  intl: ^0.17.0
  photo_view: ^0.14.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
